name: metering
services:
  db:
    profiles: [develop]
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=metering
      - POSTGRES_PASSWORD=metering
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
