spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/metering
spring.datasource.username=metering
spring.datasource.password=metering
spring.graphql.graphiql.enabled=true